### ISSUE TITLE
Ed: Include more international keyboard examples

### ISSUE THREAD

**Issue by r12a** [w3c/uievents-code#11]
1. Keyboard Layout

https://w3c.github.io/uievents-code/#keyboard-layout

There are references to Japanese and Korean keyboards, but it would be interesting to also include examples of other keyboards such as Arabic, Hindi and Khmer, to make things clearer.

**Comment by garykac** [comment]
Only keyboards that introduce new physical keys to the layout are covered in this spec.

The mentioned keyboards (Arabic, Hindi and Khmer) are all variants of the 101- and 102- keyboard layouts -- they don't add any extra keys that not found on other keyboards, they simply relabel existing keys.

**Comment by r12a** [comment]
Reopening for reply.  

I think it would be useful to put what you just said in a note in the text, since it  reduces the worry for the reader that there are keyboards that may not have been considered.

**Comment by r12a** [comment]
LTGM, thanks. I'll recommend closure of our tracker issue to the i18n WG.
