### ISSUE TITLE
i18n Issues common to main spec

### ISSUE THREAD

**Issue by r12a** [w3c/uievents-code#12]
The following issues were raised against the main UI Events spec, but are relevant to this spec also:

https://github.com/w3c/uievents/issues/127

https://github.com/w3c/uievents/issues/117

https://github.com/w3c/uievents/issues/121

**Comment by garykac** [comment]
Split into separate issues:
https://github.com/w3c/uievents-code/issues/13
https://github.com/w3c/uievents-code/issues/14
https://github.com/w3c/uievents-code/issues/15
