### ISSUE TITLE
Bikeshed syntax problem in section 3

### ISSUE THREAD

**Issue by cvrebert** [w3c/uievents-code#18]
https://w3c.github.io/uievents-code/#code-value-tables

> A key code attribute value is any of the values given in the =KeyboardEvent.code= column

The rendered HTML has literal equals-signs in it, instead of a link.

**Comment by garykac** [comment]
Fixed in https://github.com/w3c/uievents-code/commit/06bb9d098b2fca9966a9f1fd9d959c9ed7af2b43
