### ISSUE TITLE
IPR bot not enabled

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/uievents-code#29]
@siusin, seems IPR bot is not enabled for this repo. Would you mind taking a look?

**Comment by siusin** [comment]
This repo is already listed under the WebApps WG in our Repository Manager, and the setting looks good to me.

The last PR was from 2019, have you submit any code recently?  or shall we wait for the next one?

**Comment by marcoscaceres** [comment]
Oopps... ok, yep, there it is - working indeed! :) 
https://github.com/w3c/uievents-code/pull/30

Sorry about that!!!
