### ISSUE TITLE
Get horizontal review for UIEvents KeyboardEvent Code

### ISSUE THREAD

**Issue by siusin** [w3c/uievents-code#32]
Now that the spec is stable, it's time for us to ask for a wide review!

- [ ] Write a "Privacy Considerations" section for the spec, taking into account the [Self-Review Questionnaire: Security and Privacy](https://w3ctag.github.io/security-questionnaire/);
- [ ] Write a "Security Considerations" section for the spec, taking into account the [Self-Review Questionnaire: Security and Privacy](https://w3ctag.github.io/security-questionnaire/);
- [ ] work through the [Internationalisation Short Checklist](https://w3c.github.io/i18n-drafts/techniques/shortchecklist), then [request a review via GitHub](https://github.com/w3c/i18n-request/issues/new/choose);
- [ ] Work through the [Accessibility questionnaire](https://w3c.github.io/apa/fast/checklist.html) then [request a review via GitHub ](https://github.com/w3c/a11y-request/issues/new/choose).

@garykac could you take a look at these questionnaires please? @marcoscaceres and I are very willing to work with you to fulfill these tasks.

**Comment by garykac** [comment]
Closing because these have all been addressed in #35.
