### ISSUE TITLE
Possible error: "Backspace" is listed in the Writing System Keys instead of Functional Keys table

### ISSUE THREAD

**Issue by Keavon** [w3c/uievents-code#34]
The table in section 3.1.1.1 Writing System Keys includes `"Backspace"` (it is the third entry). I believe this is an error.

Figure 13, the diagram for writing system keys, does *not* highlight <kbd>Backspace</kbd>:

> ![Figure 13](https://www.w3.org/TR/uievents-code/images/keyboard-codes-alphanum1.svg)

It has 50 keys (51 including the duplicate <kbd>Backslash</kbd>) in green or blue. The (potentially) erroneous table has 51 entries (without the duplicate <kbd>Backslash</kbd>).

In the next section, 3.1.1.2 Functional Keys, the table is missing `"Backspace"` even though its figure 14 diagram *does* color in the <kbd>Backspace</kbd> key blue. Furthermore, the text above the diagram specifically calls out <kbd>Backspace</kbd> as an example of a functional key.

3.1.1.2. Functional Keys says:
> The ***functional keys*** (*not to be confused with the [function keys](https://www.w3.org/TR/uievents-code/#function-key) described later*) are those keys in the [alphanumeric section](https://www.w3.org/TR/uievents-code/#alphanumeric-section) that provide general editing functions that are common to all locales (like <kbd>Shift</kbd>, <kbd>Tab</kbd>, <kbd>Enter</kbd> and <kbd>Backspace</kbd>). With a few exceptions, these keys do not change meaning based on the current keyboard layout.
> ![Figure 14](https://www.w3.org/TR/uievents-code/images/keyboard-codes-alphanum2.svg)
> ***Figure 14*** The standard set of [functional keys](https://www.w3.org/TR/uievents-code/#functional-keys) in the [alphanumeric section](https://www.w3.org/TR/uievents-code/#alphanumeric-section)

This diagram has 14 keys in green or blue. But the table has only 13 entries. One extra entry in the Writing System Keys table and one fewer in the Functional Keys table.

Is <kbd>Backspace</kbd> a functional key or a writing system key? My conclusion is that the two tables erroneously list the `"Backspace"` entry in the wrong table.

**Comment by garykac** [comment]
Thank you for reporting this. It is fixed in the latest WD: https://w3c.github.io/uievents-code/
