### ISSUE TITLE
Unicode terminology

### ISSUE THREAD

**Issue by xfq** [w3c/uievents-code#36]
1.1 Stylistic Conventions
https://w3c.github.io/uievents-code/#style-conventions

> Unicode character encodings are shown as: U+003d.

[Unicode code point](https://w3c.github.io/i18n-glossary/#def_unicode_code_point), rather than "Unicode character encodings",  should be more accurate here. Moreover, i18n generally recommends using "A"–"F" (rather than "a"–"f") for the code point values.

**Comment by annevk** [comment]
It should reference and use the style of https://infra.spec.whatwg.org/.

**Comment by aphillips** [comment]
Adding some clarification to this issue.

As @xfq notes, "Unicode character encodings" is incorrect in this context. A Unicode character encoding would be something like UTF-8, UTF-16, etc. You actually mean Unicode code point.

Guidelines on quoting characters can be found in our Best Practices doc [here](https://w3c.github.io/bp-i18n-specdev/#char_ref).

I endorse @annevk's comment also. Note that the specific location in Infra is [here](https://infra.spec.whatwg.org/#code-points). I will update our guidance to include that location and for mutual consistency.
