### ISSUE TITLE
CFC to publish UI Events KeyboardEvent code Values as a Proposed Recommendation in the WebApps WG

### ISSUE THREAD

**Issue by siusin** [w3c/uievents-code#43]
The UI Events KeyboardEvent code Values spec has obtained [adequate implementation experience](https://w3c.github.io/uievents-code/impl-report.html), so this is a Call for Consensus to transition UI Events KeyboardEvent code Values to Proposed Recommendation.

The latest version of the spec is available at:
   https://www.w3.org/TR/uievents-code/

To show support for the transition, please add a 👍.

If you'd like to raise a Formal Objection to publishing this document, please do so by using a 👎 by 28 October, 2024.
Please include the rationale for your objection to its publication as GitHub comment or email the working group.

If you have other comments, suggestions, or found bugs, we invite you to file an issue.

**Comment by travisleithead** [comment]
Thanks @garykac! Great to see this progressing!

**Comment by LJWatson** [comment]
With multiple expressions of support and no objections, the proposal to publish The UI Events KeyboardEvent code Values spec as a PR passes.

Thanks to everyone who responded.
