### ISSUE TITLE
Mismatch between code value, Volume(Down|Up|Mute) and key value AudioVolume(Down|Up|Mut)

### ISSUE THREAD

**Issue by masayuki-nakano** [w3c/uievents-code#8]
Now, key values have "Audio" prefix for Volume(Down|Up|Mute). However, code values are still Volume(Down|Up|Mute) without prefix.

I'm not sure if this is intentional but I should file this issue.

For consistency, both of them should have same name, though.

On the other hand, I'm not sure it's worthwhile to change code value spec because Firefox already uses the values. From such point of view, it's better key values of them not to have "Audio" prefix because both IE and Firefox already use the old values.

**Comment by garykac** [comment]
sounds good. I'll update the |code| values to be AudioVolume\* to match the |key| values. This will also be good in case we ever need to add Microphone Volume |code| values.
